import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "../globals.css";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body className={`relative min-h-screen bg-zinc-950 ${ubuntu.className}`}>
        {children}
      </body>
    </html>
  );
}
